server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/proj_inov_back
    username: seu_banco
    password: sua_senha
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    client-id: ${CLIENT_ID:myclientid}
    client-secret: ${CLIENT_SECRET:myclientsecret}
    jwt:
      duration: ${JWT_DURATION:86400}

  cors:
    origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}